name: RSpec Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: myapp_test
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -ppassword"
          --health-interval=10s
          --health-timeout=10s
          --health-retries=3
          --health-start-period=30s

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.3 # 適切なRubyバージョンに合わせて変更してください
          bundler-cache: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs yarn
          gem install bundler
          bundle install
      - name: Set up database config for CI
        run: cp config/database.yml.ci config/database.yml


      - name: Prepare database
        env:
          RAILS_ENV: test
          DATABASE_URL: mysql2://root:password@127.0.0.1:3306/myapp_test
        run: |
          bin/rails db:prepare

      - name: Run RSpec
        env:
          RAILS_ENV: test
        run: |
          bundle exec rspec

